---
abstract: 'Front-end module to collect system statistics'
author:
  - 'Jonny Schulz'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sys-Statistics-Linux
provides:
  Sys::Statistics::Linux:
    file: lib/Sys/Statistics/Linux.pm
    version: 0.63
  Sys::Statistics::Linux::Compilation:
    file: lib/Sys/Statistics/Linux/Compilation.pm
    version: 0.10
  Sys::Statistics::Linux::CpuStats:
    file: lib/Sys/Statistics/Linux/CpuStats.pm
    version: 0.20
  Sys::Statistics::Linux::DiskStats:
    file: lib/Sys/Statistics/Linux/DiskStats.pm
    version: 0.24
  Sys::Statistics::Linux::DiskUsage:
    file: lib/Sys/Statistics/Linux/DiskUsage.pm
    version: 0.14
  Sys::Statistics::Linux::FileStats:
    file: lib/Sys/Statistics/Linux/FileStats.pm
    version: 0.09
  Sys::Statistics::Linux::LoadAVG:
    file: lib/Sys/Statistics/Linux/LoadAVG.pm
    version: 0.08
  Sys::Statistics::Linux::MemStats:
    file: lib/Sys/Statistics/Linux/MemStats.pm
    version: 0.16
  Sys::Statistics::Linux::NetStats:
    file: lib/Sys/Statistics/Linux/NetStats.pm
    version: 0.21
  Sys::Statistics::Linux::PgSwStats:
    file: lib/Sys/Statistics/Linux/PgSwStats.pm
    version: 0.18
  Sys::Statistics::Linux::ProcStats:
    file: lib/Sys/Statistics/Linux/ProcStats.pm
    version: 0.20
  Sys::Statistics::Linux::Processes:
    file: lib/Sys/Statistics/Linux/Processes.pm
    version: 0.36
  Sys::Statistics::Linux::SockStats:
    file: lib/Sys/Statistics/Linux/SockStats.pm
    version: 0.09
  Sys::Statistics::Linux::SysInfo:
    file: lib/Sys/Statistics/Linux/SysInfo.pm
    version: 0.13
recommends:
  YAML::Syck: 0
requires:
  Carp: 0
  POSIX: 0
  Test::More: 0
  Time::HiRes: 0
  UNIVERSAL: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.63
